sudo: required

language: python

python:
- '3.6'

install:
- pip install codecov
- pip install pylint

script:
- nosetests --with-coverage --cover-package=v_log --cover-erase --cover-inclusive

after_success:
- codecov

notifications:
  email:
    on_success: never # default: change
    on_failure: never # default: always
